- name: Configure NetmodX Env
  hosts: pi1
  vars_files:
    - creds.yml
  tasks:
    - import_tasks: roles/core.yml
    - import_tasks: roles/ditto.yml
    - import_tasks: roles/dev.yml
    - import_tasks: roles/docker.yml
