---
- name: Configure NetModX rPis Env
  hosts: rpis
  vars_files:
      - creds.yml
  tasks:
    - import_tasks: roles/core.yml
      tags: core
    - import_tasks: roles/dev.yml
      tags: dev
    - import_tasks: roles/docker.yml
      tags: docker
    - import_tasks: roles/ditto.yml
      tags: ditto
    #    - import_tasks: roles/sensehat-node-ipc.yml
    #  tags: sni
- name: Configure FOB
  hosts: fob
  vars_files:
    - creds.yml
  tasks:
    - import_tasks: roles/core.yml
      tags: core
    - import_tasks: roles/dev.yml
      tags: dev
    - import_tasks: roles/docker.yml
      tags: docker
    - import_tasks: roles/ditto.yml
      tags: ditto
