- name: Clone ditto-to-redpanda Repo 
  git:
    repo: https://github.com/getditto-shared/ditto-to-redpanda
    dest: "{{ ansible_user_dir }}/ditto-to-redpanda"
    clone: yes
    update: yes
  tags: collector

- name: Run npm ci
  shell: |
    export NVM_DIR="{{ ansible_user_dir }}/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    cd {{ ansible_user_dir }}/ditto-to-redpanda
    npm i -g typescript
    npm ci --no-progress
  tags: collector

- name: Place .env file
  ansible.builtin.template:
    src: templates/collector_env.j2
    dest: "{{ ansible_user_dir }}/ditto-to-redpanda/.env"
    mode: '0600'

- name: Install pm2 
  shell: |
    export NVM_DIR="{{ ansible_user_dir }}/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    cd {{ ansible_user_dir }}/ditto-to-redpanda
    npm install -g pm2 
  tags: collector

- name: Run tsc compile
  shell: |
    export NVM_DIR="{{ ansible_user_dir }}/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    cd {{ ansible_user_dir }}/ditto-to-redpanda
    tsc index.ts
  tags: collector

- name: Start myapp.js, if not running
  pm2:
    name: collector
    chdir: "{{ ansible_user_dir }}/ditto-to-redpanda"
    script: "node index.js"
    state: started
