- name: Clone sensehat-node-ipc repository
  git:
    repo: 'https://github.com/Marco-Christiani/sensehat-node-ipc.git'
    dest: "{{ ansible_user_dir }}/sensehat-node-ipc"
    clone: yes
    update: yes
  tags: sni-install

- name: Run npm ci
  command:
    cmd: npm ci --no-progress
    chdir: "{{ ansible_user_dir }}/sensehat-node-ipc"
  tags: sni-install

- name: Run npm run clean-build
  command:
    cmd: npm run clean-build
    chdir: "{{ ansible_user_dir }}/sensehat-node-ipc"
  tags: sni-install

- name: Run npm test
  command:
    cmd: npm test
    chdir: "{{ ansible_user_dir }}/sensehat-node-ipc"
  tags: sni-test
